#!/usr/bin/env bash
set -eu

# This script is simply used to ensure the most recent jar file and kernel.json file
# are copied into the working directory before running the docker build.

# Parse the latest VERSION. The VERSION file is generated by Maven during the build.
VERSION=`cat ../../VERSION`

# The name of the jar file generated by Maven.
jar=jupyter-groovy-kernel-$VERSION.jar

# Where the latest jar file can be located
targetjar=../../target/$jar

if [ ! -e $targetjar ] ; then
    echo "JAR file not found. Building it now"
    cd ../../
    mvn clean package
    # We need to parse the VERSION file again.
    VERSION=`cat VERSION`
    cd -
fi

# The location of the kernel.json template.
kernel=../../src/distribution/kernel.json

if [ ! -e $jar ] || [ $targetjar -nt $jar ] ; then
    echo "Copying $targetjar"
    cp $targetjar .
fi

if [ ! -e kernel.json ] || [ $kernel -nt kernel.json ] ; then
    echo "Patching the kernel.json file"
    cat $kernel | sed "s|__PATH__|/opt/groovy/$jar|" > kernel.json
fi

echo "Building the Docker container with $jar"
docker build --build-arg VERSION=$VERSION -t lappsgrid/jupyter-groovy-kernel $@ .

